export { default as Point } from './Point'
export { default as Dimension } from './Dimension'
export { default as Rectangle } from './Rectangle'
export { default as LineSegment } from './LineSegment'
export { default as Line } from './Line'
export { point, dimension, rectangle, lineSegment, line } from './factories'
