export { default as Point } from './Point'
export { default as Dimension } from './Dimension'
export { default as Rectangle } from './Rectangle'
export { default as LineSegment } from './LineSegment'
export { point, dimension, rectangle, lineSegment } from './factories'
